---
- name: Install APT https transport
  apt:
    name: apt-transport-https
    state: present

- name: Add Elasticsearch APT key
  apt_key:
    url: 'http://packages.elasticsearch.org/GPG-KEY-elasticsearch'
    id: '{{ elasticsearch_key_id }}'
    state: present

- name: Add Elasticsearch repository
  apt_repository:
    repo: 'deb {{ elasticsearch_repository }}/{{ elasticsearch_version if (elasticsearch__version_major | int == 1) else (elasticsearch__version_major + ".x") }}/debian stable main'
    state: present
  when: elasticsearch__version_major | int <= 2

- name: Add Elasticsearch repository
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ elasticsearch__version_major }}.x/apt stable main'
    state: present
  when: elasticsearch__version_major | int > 2

- name: Install Elasticsearch
  apt:
    pkg: 'elasticsearch={{ elasticsearch_version }}.*'
    state: present
    update_cache: true
    install_recommends: false
  when: not elasticsearch_version_exact

- name: Install Elasticsearch exact version
  apt:
    pkg: 'elasticsearch={{ elasticsearch_version }}'
    state: present
    update_cache: true
    install_recommends: false
  when: elasticsearch_version_exact

- name: Configure Elasticsearch
  template:
    src: '{{ item[1:] }}.j2'
    dest: '{{ item }}'
    owner: 'root'
    group: 'elasticsearch'
    mode: '0640'
  with_items:
    - '/etc/default/elasticsearch'
    - '{{ elasticsearch_path_conf }}/elasticsearch.yml'
    - '{{ elasticsearch_path_conf }}/logging.yml'
  notify: [ 'Restart Elasticsearch' ]

- name: Start Elasticsearch
  service:
    name: 'elasticsearch'
    state: started
    enabled: true
  register: elastic_start

- name: Wait for ElasticSearch to come up
  wait_for:
    port: 9200
    delay: 15
    host: localhost
  when: elastic_start.changed
  tags:
    - skip_ansible_lint
