---

- name: Add Elasticsearch APT key
  apt_key:
    url: 'http://packages.elasticsearch.org/GPG-KEY-elasticsearch'
    id: '{{ elasticsearch_key_id }}'
    state: present

- name: Add Elasticsearch repository
  apt_repository:
    repo: 'deb {{ elasticsearch_repository }}/{{ elasticsearch_version if (elasticsearch__version_major | int == 1) else (elasticsearch__version_major + ".x") }}/debian stable main'
    state: present
    update_cache: True
  when: elasticsearch__version_major | int <= 2

- name: Add Elasticsearch repository
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ elasticsearch__version_major }}.x/apt stable main'
    state: present
    update_cache: True
  when: elasticsearch__version_major | int > 2

- name: Install Elasticsearch
  apt:
    pkg: 'elasticsearch'
    state: present
    install_recommends: False

- name: Divert original configs
  command: dpkg-divert --quiet --local --divert {{ elasticsearch_path_conf }}/{{ item }}.yml.dpkg-divert --rename {{ elasticsearch_path_conf }}/{{ item }}.yml creates={{ elasticsearch_path_conf }}/{{ item }}.yml.dpkg-divert
  with_items: [ 'elasticsearch', 'logging' ]

- name: Configure Elasticsearch
  template:
    src: '{{ item[1:] }}.j2'
    dest: '{{ item }}'
    owner: 'root'
    group: 'elasticsearch'
    mode: '0640'
  with_items:
    - '/etc/default/elasticsearch'
    - '{{ elasticsearch_path_conf }}/elasticsearch.yml'
    - '{{ elasticsearch_path_conf }}/logging.yml'
  notify: [ 'Restart Elasticsearch' ]

- name: Start Elasticsearch
  service:
    name: 'elasticsearch'
    state: started
    enabled: True
