---

- name: Detect installed libs
  command: ls
  args:
    chdir: '{{ elasticsearch_path_lib }}'
  changed_when: False
  register: elasticsearch_register_installed_libs

- name: Delete libs
  file:
    path: '{{ elasticsearch_path_lib }}/{{ item.file | default(item.url.split("/")[-1]) }}'
    state: absent
  when: item.delete is defined and item.delete and
        item.file | default(item.url.split('/')[-1]) in elasticsearch_register_installed_libs.stdout
  with_items: '{{ elasticsearch_libs }}'
  notify: [ 'Restart Elasticsearch' ]

- name: Install custom libs
  get_url:
    url: '{{ item.url }}'
    dest: '{{ elasticsearch_path_lib }}/{{ item.file | default(item.url.split("/")[-1]) }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    url_username: '{{ item.user | default(omit) }}'
    url_password: '{{ item.pass | default(omit) }}'
  when: (item.delete is undefined or not item.delete) and
        not item.file | default(item.url.split('/')[-1]) in elasticsearch_register_installed_libs.stdout
  with_items: '{{ elasticsearch_libs }}'
  notify: [ 'Restart Elasticsearch' ]
