---
- name: Converge
  hosts: all
  become: true
  vars:
    elasticsearch_version: '6.2.4'
    elasticsearch_plugins:
      - { name: 'analysis-icu' }
  roles:
    - role: ansible-role-elasticsearch
